platform:
  filename: "ColorChecker_2592x1536_12bits_RGGB.raw"
  disable_progress_bar: false
  leave_pbar_string: false
  render_3a: false
  save_format: "both"

# Global fixed-point arithmetic configuration
fixed_point_config:
  # Precision mode: "8bit" (fast) or "16bit" (precise)
  precision_mode: "8bit"
  # Fractional bits for 8-bit mode (4-7 bits recommended)
  fractional_bits_8bit: 6
  # Fractional bits for 16-bit mode (8-14 bits recommended)  
  fractional_bits_16bit: 12
  # Enable fixed-point arithmetic for all modules after demosaic
  enable_fixed_point: true

sensor_info:
  bayer_pattern: "rggb"
  range: 4095
  bit_depth: 12
  width: 2592
  height: 1536

black_level_correction:
  is_enable: true
  r_offset: 200
  gr_offset: 200
  gb_offset: 200
  b_offset: 200
  is_linear: false
  r_sat: 4095
  gr_sat: 4095
  gb_sat: 4095
  b_sat: 4095
  is_save: false

white_balance:
  is_enable: true
  is_debug: true
  is_auto: true
  r_gain: 1.24609375
  b_gain: 2.80859375
  is_save: false

demosaic:
  is_save: false

color_correction_matrix:
  is_enable: true
  corrected_red: [1.660, -0.527, -0.133]
  corrected_green: [-0.408, 1.563, -0.082]
  corrected_blue: [-0.055, -1.641, 2.695]
  is_save: false
  # Module-specific fixed-point override (optional)
  # use_fixed_point: true
  # fixed_point_bits: 8

gamma_correction:
  is_enable: true
  is_save: false 