platform:
  filename: "test.raw"
  disable_progress_bar: false
  leave_pbar_string: false
  render_3a: false
  save_format: "both"

sensor_info:
  bayer_pattern: "rggb"
  range: 4095
  bit_depth: 12
  width: 2592
  height: 1536

rgb_conversion:
  is_enable: true
  is_save: false
  is_debug: false 